config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :questions do
    resources :answers
  end
  
  root 'welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :article
  validates :answer, presence: true, length: { minimum: 5 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/answer_controller.rb
class AnswerController < ApplicationController
  def create
    @question = Question.find(params[:question_id])
    @answer = @article.answers.create(answer_params)
    redirect_to article_path(@article)
  end

  private

  def answer_params
    params.require(:comment).permit(:answer)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    def new
        @question = Question.new
    end

    def create
        @question = Question.new(params.require(:question).permit(:title,:text))
        if @question.save
            redirect_to @question
        else
           render 'new'
        end
    end

    def show
        @question = Question.find(params[:id])
    end
    def index
        @questions = Question.all
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @questions = Question.all
  end
end

app/helpers/answer_helper.rb
module AnswerHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <title>Intunderflow</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h1>All Questions</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <td><%= question.text %></td>
      <td><%= link_to 'Show', question_path(question) %></td>
    </tr>
  <% end %>
</table>

app/views/questions/new.html.erb
<%# Disable turbo as it was messing up validation. %>
<%= form_for :question, url: questions_path, data: { turbo:false} do |f| %>  

<% if @question.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@question.errors.count, "error") %> prohibited
        this question from being saved:
      </h2>
      <ul>
        <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/questions/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @question.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @question.text %>
</p>

<%= form_for([@question, @question.answers.build]) do |f| %>
  <p>
    <%= f.label :answer %><br>
    <%= f.text_area :answer %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', questions_path %>

app/views/welcome/index.html.erb
<h1>Integer Underflow</h1>

<div>
Welcome to Integer Underflow!  Got a <%= link_to 'programming question?', new_question_path %>
</div>

<div>
<h3>Latest Questions:</h3>
<table> 
  <% @questions.each do |question| %>
    <tr>
      <td><%= question.title %></td>
      <td><%= link_to 'Answer', question_path(question) %></td>
    </tr>
  <% end %>
</table>
</div>

<%= link_to 'All Questions!', controller: 'questions' %>